local vim = vim
local Plug = vim.fn['plug#']

vim.call('plug#begin')
Plug('rebelot/kanagawa.nvim')
Plug('nvim-lua/plenary.nvim')
Plug('nvim-tree/nvim-web-devicons')
Plug('MunifTanjim/nui.nvim')
Plug('nvim-neo-tree/neo-tree.nvim', { ['branch'] = 'v3.x' })
Plug('romgrk/barbar.nvim')
Plug('nvim-lualine/lualine.nvim')
Plug('nvim-treesitter/nvim-treesitter', { ['do'] = ':TSUpdate' })
Plug('neovim/nvim-lspconfig')
Plug('hrsh7th/cmp-buffer')
Plug('hrsh7th/cmp-path')
Plug('hrsh7th/cmp-cmdline')
Plug('hrsh7th/nvim-cmp')
Plug('hrsh7th/cmp-nvim-lsp')
Plug('hrsh7th/cmp-nvim-lsp-signature-help')
Plug('hrsh7th/cmp-vsnip')
Plug('hrsh7th/vim-vsnip')
Plug('rmagatti/auto-session')
Plug('olimorris/codecompanion.nvim', { ['tag'] = 'v19.*' })
vim.call('plug#end')

package.path = package.path .. ";" .. os.getenv("HOME") .. "/.config/nvim/?.lua"

require("common")
require("theme")
require("neotree")
require("barbar-config")
require("lua_line")
require("treesitter")
require("lsp")
require("cmp_config")
require("session")

vim.keymap.set('n', '<C-S-Up>', '<C-W>K', { desc = 'Move split up' })
vim.keymap.set('n', '<C-S-Down>', '<C-W>J', { desc = 'Move split down' })
vim.keymap.set('n', '<C-S-Left>', '<C-W>H', { desc = 'Move split left' })
vim.keymap.set('n', '<C-S-Right>', '<C-W>L', { desc = 'Move split right' })